### ISSUE TITLE
Restart UX gateway fails

### ISSUE THREAD

**Issue by EgoManiac** [plessisa/RibbonEdgePsRest#2]
This is awesome, thank you for building this, and I will certainly be contributing to it.

But first issue to contribute. Restart-UXgateway 
`Unable to convert received data into XML correctly. The error message is Exception calling "Substring" with "2" argument(s): "StartIndex cannot be less than zero.`

This is against Ribbon ver 8. - might also be a good idea to use -force parameter for this just incase someone tabs into this cmdlet.

**Comment by plessisa** [comment]
Hi @EgoManiac,
Any chance you can attached the exacts commands you typed before getting this error?
Best,

**Comment by EgoManiac** [comment]
Hi @plessisa .

No worries, I am fixing it now. I can see the code is trying to manually create the XML. I have forked the code and creating an upto date version which is a little more modular and flexible.

As soon as i get to the reboot section I'll drop you a message with the fix.

Regards

**Comment by EgoManiac** [comment]
Hi Plessisa,

Ok, I have finally completed the fork and updated the script. It is substantially different so rather than me sending a PR you may want to take a look.

The issue was because you had some bad XML parsing going on, I assumed it was due to a copy of another function. Anyway all fixed.

https://github.com/EgoManiac/RibbonEdgePsRest

Chris
